### ISSUE TITLE
Not running as daemon(?)

### ISSUE THREAD

**Issue by HackaN** [craftyguy/autolight#4]
I installed autolight via AUR and I can run it from CL with "autolight", but it just runs for a moment and then dissapears. So if I want to the brightness to adjust again I have to run it from the CL once more.

Did I miss something with how autolight is supposed to be used?

Also, like every other time I run autolight I get an error output:
```
$ autolight
Traceback (most recent call last):
  File "/usr/bin/autolight", line 177, in <module>
    CONF['MAX_BRIGHT'], CONF['MIN_ILLUM'])
  File "/usr/bin/autolight", line 68, in calc_brightness
    brightness = math.log(illum - (min_i - 1)) * 10
ValueError: math domain error

```

Running Antergos (deepin 15.5)

**Comment by craftyguy** [comment]
What do you have set for `MIN_ILLUM` in your config? If I had to guess, though, `illum` is being set to either 0 or some negative number, such that the app is trying to find the logarithm of a number <= 0 (resulting in the domain error).

What do you see in `/sys/bus/iio/devices/iio:device0/in_illuminance_raw` ?

**Comment by HackaN** [comment]
I haven't changed any values, everything in the config is the default created by the install of Autolight.

I will check it out when I get home tonight as well as what's in "in_illuminance_raw"

**Comment by HackaN** [comment]
It fixes the error-message. But autolight is still just running for a moment when I execute it from CL.

Also if I bring the brightness up to max and place myself in a dark room autolight doesn't seem to lower the brightness. But if I have the brightness low and stand under a lamp it does bring the brightness up... And if I move away quickly enough before the process ends it does lower the brightness a little bit.

But to start in darkness doesn't seem to trigger anything.

**Comment by craftyguy** [comment]
> But autolight is still just running for a moment when I execute it from CL.

I have added another commit to PR #5 that hopefully makes calling `light` a little more robust. I'm not sure where in the app it is returning for you though.. Can you try the updated PR #5 and see if that helps? If not, would you be able to run the app in a debugger (e.g. pdb) to see where exactly it is returning for you?

> But to start in darkness doesn't seem to trigger anything.

You will need to adjust the MIN_ILLUM value to something lower. It seems your device is reporting values that are lower than the device I use (e.g. `18` vs `22`). A good way to find the lowest value your device will report is to go into a dark room, cover the sensor with your thumb, and read `/sys/bus/iio/devices/iio:device0/in_illuminance_raw`.

**Comment by HackaN** [comment]
I changed MIN_ILLUM to 1 and then to 0. I also updated /usr/bin/autolight - still doesn't change the brightness when starting in dark surrounding and still just runs for a moment :-/


To me it seems that when "in_illuminance_raw" gets to (or is at) "0" autolight stops. It seems to be running fine above "0".

**Comment by craftyguy** [comment]
Ok, I have fixed another issue with illum being <= 0 (it should never be reported as <0 by the driver, I would thing, but doesn't hurt to not assume!). Can you try the latest commit in PR #5 and let me know if that helps?

I apologize for the guess work on my behalf, but I don't have a way to directly reproduce exactly what you are seeing :(

**Comment by HackaN** [comment]
It is really strange, but the same thing keeps happening. When /sys/bus/iio/devices/iio:device0/in_illuminance_raw is 0 autolight stops. I am running Antergos on a MacBook Air (if that helps or could have any significance).

**Comment by craftyguy** [comment]
Can you use a debugger (like pdb ) to figure out where it is returning?

**Comment by craftyguy** [comment]
I think I see what the issue is. Line number 174 quits if illum is 0, which I thought would only be the case if it couldn't read from the device. I'll correct this in the PR #5 branch soon.

**Comment by craftyguy** [comment]
@HackaN 

can you try the latest in #5 and let me know how that goes?
